/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    pages: Page;
    posts: Post;
    announcements: Announcement;
    chapters: Chapter;
    chapterRequests: ChapterRequest;
    membershipPlans: MembershipPlan;
    memberships: Membership;
    events: Event;
    eventRegistrations: EventRegistration;
    waitlistEntries: WaitlistEntry;
    orders: Order;
    payments: Payment;
    promotions: Promotion;
    committeeTerms: CommitteeTerm;
    historyEntries: HistoryEntry;
    newsletterCampaigns: NewsletterCampaign;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    chapters: ChaptersSelect<false> | ChaptersSelect<true>;
    chapterRequests: ChapterRequestsSelect<false> | ChapterRequestsSelect<true>;
    membershipPlans: MembershipPlansSelect<false> | MembershipPlansSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    eventRegistrations: EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    waitlistEntries: WaitlistEntriesSelect<false> | WaitlistEntriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    committeeTerms: CommitteeTermsSelect<false> | CommitteeTermsSelect<true>;
    historyEntries: HistoryEntriesSelect<false> | HistoryEntriesSelect<true>;
    newsletterCampaigns: NewsletterCampaignsSelect<false> | NewsletterCampaignsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    header: Header;
    footer: Footer;
    home: Home;
    seoDefaults: SeoDefault;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    seoDefaults: SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role: 'member' | 'chapterAdmin' | 'admin' | 'superAdmin';
  accountStatus: 'pending' | 'active' | 'suspended' | 'deleted';
  primaryChapter?: (number | null) | Chapter;
  managedChapters?: (number | Chapter)[] | null;
  phoneNumber?: string | null;
  ruetDepartment?: string | null;
  graduationYear?: number | null;
  alumniReference?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  employer?: string | null;
  professionalTitle?: string | null;
  communicationPreferences?: {
    allowAnnouncements?: boolean | null;
    allowNewsletters?: boolean | null;
    allowSystemEmails?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters".
 */
export interface Chapter {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  chapterStatus: 'active' | 'inactive' | 'planning';
  regionOrState?: string | null;
  summary: string;
  description?: string | null;
  chapterAdmins?: (number | User)[] | null;
  contactEmail?: string | null;
  heroImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroDescription?: string | null;
  summary?: string | null;
  sections?:
    | {
        eyebrow?: string | null;
        title: string;
        body: string;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt: string;
  body: string;
  featuredImage?: (number | null) | Media;
  categories?: (number | Category)[] | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  summary: string;
  details?: string | null;
  chapter?: (number | null) | Chapter;
  audience: 'public' | 'members';
  tone?: ('info' | 'success' | 'alert') | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  activeFrom?: string | null;
  activeTo?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapterRequests".
 */
export interface ChapterRequest {
  id: number;
  requestedName: string;
  requester: number | User;
  status: 'pending' | 'approved' | 'rejected';
  notes?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membershipPlans".
 */
export interface MembershipPlan {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  publicSummary?: string | null;
  benefits?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  annualPrice: number;
  currency: string;
  active?: boolean | null;
  autoRenewEnabled?: boolean | null;
  gracePeriodDays?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  user: number | User;
  plan: number | MembershipPlan;
  status:
    | 'pending_payment'
    | 'pending_manual_approval'
    | 'active'
    | 'grace_period'
    | 'expired'
    | 'failed_manual_payment'
    | 'cancelled_by_admin'
    | 'suspended';
  startedAt?: string | null;
  renewalAt?: string | null;
  expiresAt?: string | null;
  graceEndsAt?: string | null;
  autoRenewEnabled?: boolean | null;
  paymentMethod?: ('stripe' | 'zelle') | null;
  chapterSnapshot?: string | null;
  planTitleSnapshot?: string | null;
  planPriceSnapshot?: number | null;
  currencySnapshot?: string | null;
  billingIntervalSnapshot?: string | null;
  reactivationEligible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  chapter: number | Chapter;
  status: 'draft' | 'published' | 'archived';
  eventMode: 'inPerson' | 'virtual' | 'hybrid';
  startAt: string;
  endAt: string;
  timezone: 'America/New_York' | 'America/Chicago' | 'America/Denver' | 'America/Los_Angeles';
  venue?: string | null;
  virtualLink?: string | null;
  virtualAccessVisibility?: ('public' | 'registered') | null;
  summary: string;
  details?: string | null;
  featuredImage?: (number | null) | Media;
  isPaid?: boolean | null;
  basePrice?: number | null;
  currency?: string | null;
  capacity?: number | null;
  waitlistEnabled?: boolean | null;
  maxRegistrationQuantity?: number | null;
  galleryAfterCompletion?: (number | Media)[] | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  user: number | User;
  quantity: number;
  status: 'pending' | 'confirmed' | 'waitlisted' | 'cancelled';
  order?: (number | null) | Order;
  paymentStatus?: ('pending' | 'paid' | 'failed') | null;
  registrationPriceSnapshot?: number | null;
  discountSnapshot?: number | null;
  waitlistPosition?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  user: number | User;
  orderType: 'membership' | 'event';
  chapterAttribution?: (number | null) | Chapter;
  status: 'pending' | 'paid' | 'failed' | 'cancelled';
  subtotal: number;
  discountTotal?: number | null;
  total: number;
  currency: string;
  paymentMethod?: ('stripe' | 'zelle') | null;
  stripeSessionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlistEntries".
 */
export interface WaitlistEntry {
  id: number;
  event: number | Event;
  user: number | User;
  quantity: number;
  joinedAt: string;
  status: 'waiting' | 'promoted' | 'expired';
  promotedAt?: string | null;
  promotionExpiryAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  user: number | User;
  order: number | Order;
  paymentSource: 'stripe' | 'zelle';
  status: 'pending' | 'approved' | 'failed';
  externalReference?: string | null;
  proofImage?: (number | null) | Media;
  proofTransactionId?: string | null;
  submittedAt?: string | null;
  firstReviewerChapter?: (number | null) | Chapter;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  rejectedBy?: (number | null) | User;
  rejectedAt?: string | null;
  rejectionReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  code: string;
  scope: 'membership' | 'event' | 'both';
  discountType: 'fixed' | 'percent';
  discountValue: number;
  startsAt?: string | null;
  endsAt?: string | null;
  usageLimit?: number | null;
  active?: boolean | null;
  memberOnly?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committeeTerms".
 */
export interface CommitteeTerm {
  id: number;
  committeeType: 'running' | 'advisory';
  chapter?: (number | null) | Chapter;
  title: string;
  startDate: string;
  endDate: string;
  isCurrent?: boolean | null;
  members?:
    | {
        name: string;
        role: string;
        photo?: (number | null) | Media;
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  eventRecaps?:
    | {
        title: string;
        eventDate?: string | null;
        summary: string;
        photoGallery?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "historyEntries".
 */
export interface HistoryEntry {
  id: number;
  title: string;
  startYear: number;
  endYear?: number | null;
  summary: string;
  body?: string | null;
  images?: (number | Media)[] | null;
  externalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletterCampaigns".
 */
export interface NewsletterCampaign {
  id: number;
  title: string;
  subject: string;
  summary?: string | null;
  body: string;
  audience: 'all' | 'members';
  status: 'draft' | 'scheduled' | 'sent';
  scheduledAt?: string | null;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'chapters';
        value: number | Chapter;
      } | null)
    | ({
        relationTo: 'chapterRequests';
        value: number | ChapterRequest;
      } | null)
    | ({
        relationTo: 'membershipPlans';
        value: number | MembershipPlan;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'eventRegistrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'waitlistEntries';
        value: number | WaitlistEntry;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'committeeTerms';
        value: number | CommitteeTerm;
      } | null)
    | ({
        relationTo: 'historyEntries';
        value: number | HistoryEntry;
      } | null)
    | ({
        relationTo: 'newsletterCampaigns';
        value: number | NewsletterCampaign;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  accountStatus?: T;
  primaryChapter?: T;
  managedChapters?: T;
  phoneNumber?: T;
  ruetDepartment?: T;
  graduationYear?: T;
  alumniReference?: T;
  city?: T;
  state?: T;
  country?: T;
  employer?: T;
  professionalTitle?: T;
  communicationPreferences?:
    | T
    | {
        allowAnnouncements?: T;
        allowNewsletters?: T;
        allowSystemEmails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  heroEyebrow?: T;
  heroTitle?: T;
  heroDescription?: T;
  summary?: T;
  sections?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  body?: T;
  featuredImage?: T;
  categories?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  details?: T;
  chapter?: T;
  audience?: T;
  tone?: T;
  ctaLabel?: T;
  ctaHref?: T;
  activeFrom?: T;
  activeTo?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters_select".
 */
export interface ChaptersSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  chapterStatus?: T;
  regionOrState?: T;
  summary?: T;
  description?: T;
  chapterAdmins?: T;
  contactEmail?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapterRequests_select".
 */
export interface ChapterRequestsSelect<T extends boolean = true> {
  requestedName?: T;
  requester?: T;
  status?: T;
  notes?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membershipPlans_select".
 */
export interface MembershipPlansSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  publicSummary?: T;
  benefits?:
    | T
    | {
        label?: T;
        id?: T;
      };
  annualPrice?: T;
  currency?: T;
  active?: T;
  autoRenewEnabled?: T;
  gracePeriodDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  user?: T;
  plan?: T;
  status?: T;
  startedAt?: T;
  renewalAt?: T;
  expiresAt?: T;
  graceEndsAt?: T;
  autoRenewEnabled?: T;
  paymentMethod?: T;
  chapterSnapshot?: T;
  planTitleSnapshot?: T;
  planPriceSnapshot?: T;
  currencySnapshot?: T;
  billingIntervalSnapshot?: T;
  reactivationEligible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  chapter?: T;
  status?: T;
  eventMode?: T;
  startAt?: T;
  endAt?: T;
  timezone?: T;
  venue?: T;
  virtualLink?: T;
  virtualAccessVisibility?: T;
  summary?: T;
  details?: T;
  featuredImage?: T;
  isPaid?: T;
  basePrice?: T;
  currency?: T;
  capacity?: T;
  waitlistEnabled?: T;
  maxRegistrationQuantity?: T;
  galleryAfterCompletion?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  quantity?: T;
  status?: T;
  order?: T;
  paymentStatus?: T;
  registrationPriceSnapshot?: T;
  discountSnapshot?: T;
  waitlistPosition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlistEntries_select".
 */
export interface WaitlistEntriesSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  quantity?: T;
  joinedAt?: T;
  status?: T;
  promotedAt?: T;
  promotionExpiryAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  user?: T;
  orderType?: T;
  chapterAttribution?: T;
  status?: T;
  subtotal?: T;
  discountTotal?: T;
  total?: T;
  currency?: T;
  paymentMethod?: T;
  stripeSessionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  user?: T;
  order?: T;
  paymentSource?: T;
  status?: T;
  externalReference?: T;
  proofImage?: T;
  proofTransactionId?: T;
  submittedAt?: T;
  firstReviewerChapter?: T;
  approvedBy?: T;
  approvedAt?: T;
  rejectedBy?: T;
  rejectedAt?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  code?: T;
  scope?: T;
  discountType?: T;
  discountValue?: T;
  startsAt?: T;
  endsAt?: T;
  usageLimit?: T;
  active?: T;
  memberOnly?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committeeTerms_select".
 */
export interface CommitteeTermsSelect<T extends boolean = true> {
  committeeType?: T;
  chapter?: T;
  title?: T;
  startDate?: T;
  endDate?: T;
  isCurrent?: T;
  members?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        bio?: T;
        id?: T;
      };
  eventRecaps?:
    | T
    | {
        title?: T;
        eventDate?: T;
        summary?: T;
        photoGallery?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "historyEntries_select".
 */
export interface HistoryEntriesSelect<T extends boolean = true> {
  title?: T;
  startYear?: T;
  endYear?: T;
  summary?: T;
  body?: T;
  images?: T;
  externalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletterCampaigns_select".
 */
export interface NewsletterCampaignsSelect<T extends boolean = true> {
  title?: T;
  subject?: T;
  summary?: T;
  body?: T;
  audience?: T;
  status?: T;
  scheduledAt?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  organizationName: string;
  tagline?: string | null;
  primaryEmail?: string | null;
  utilityMessage?: string | null;
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  utilityLinks?:
    | {
        link: {
          label: string;
          href: string;
          description?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  mainLinks?:
    | {
        link: {
          label: string;
          href: string;
          description?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  primaryCtaLabel: string;
  primaryCtaHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  groups?:
    | {
        title: string;
        links?:
          | {
              link: {
                label: string;
                href: string;
                description?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletterTitle?: string | null;
  newsletterSummary?: string | null;
  legalNotice?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroDescription?: string | null;
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  membershipSectionTitle?: string | null;
  membershipSectionDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoDefaults".
 */
export interface SeoDefault {
  id: number;
  titleSuffix?: string | null;
  defaultDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  organizationName?: T;
  tagline?: T;
  primaryEmail?: T;
  utilityMessage?: T;
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  utilityLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
        id?: T;
      };
  mainLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
        id?: T;
      };
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  groups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  newsletterTitle?: T;
  newsletterSummary?: T;
  legalNotice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroDescription?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  membershipSectionTitle?: T;
  membershipSectionDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoDefaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  titleSuffix?: T;
  defaultDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'announcements';
          value: number | Announcement;
        } | null)
      | ({
          relationTo: 'chapters';
          value: number | Chapter;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null)
      | ({
          relationTo: 'committeeTerms';
          value: number | CommitteeTerm;
        } | null)
      | ({
          relationTo: 'historyEntries';
          value: number | HistoryEntry;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}