/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    oauthSessions: OauthSession;
    media: Media;
    paymentProofs: PaymentProof;
    categories: Category;
    contactSubmissions: ContactSubmission;
    emailDeliveries: EmailDelivery;
    pages: Page;
    posts: Post;
    announcements: Announcement;
    chapters: Chapter;
    chapterRequests: ChapterRequest;
    membershipPlans: MembershipPlan;
    memberships: Membership;
    events: Event;
    eventRegistrations: EventRegistration;
    waitlistEntries: WaitlistEntry;
    orders: Order;
    payments: Payment;
    auditLogs: AuditLog;
    promotions: Promotion;
    committeeTerms: CommitteeTerm;
    historyEntries: HistoryEntry;
    newsletterCampaigns: NewsletterCampaign;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    oauthSessions: OauthSessionsSelect<false> | OauthSessionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    paymentProofs: PaymentProofsSelect<false> | PaymentProofsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    contactSubmissions: ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    emailDeliveries: EmailDeliveriesSelect<false> | EmailDeliveriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    chapters: ChaptersSelect<false> | ChaptersSelect<true>;
    chapterRequests: ChapterRequestsSelect<false> | ChapterRequestsSelect<true>;
    membershipPlans: MembershipPlansSelect<false> | MembershipPlansSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    eventRegistrations: EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    waitlistEntries: WaitlistEntriesSelect<false> | WaitlistEntriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    auditLogs: AuditLogsSelect<false> | AuditLogsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    committeeTerms: CommitteeTermsSelect<false> | CommitteeTermsSelect<true>;
    historyEntries: HistoryEntriesSelect<false> | HistoryEntriesSelect<true>;
    newsletterCampaigns: NewsletterCampaignsSelect<false> | NewsletterCampaignsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    header: Header;
    footer: Footer;
    home: Home;
    seoDefaults: SeoDefault;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    seoDefaults: SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      deliverEmail: DeliverEmailJobInput;
      eventLifecycle: EventLifecycleJobInput;
      membershipLifecycle: MembershipLifecycleJobInput;
      newsletterLifecycle: NewsletterLifecycleJobInput;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role: 'member' | 'chapterAdmin' | 'admin' | 'superAdmin';
  accountStatus: 'pending' | 'active' | 'suspended' | 'deleted';
  authMethods?: ('password' | 'google')[] | null;
  googleSubject?: string | null;
  profileStatus?: ('incomplete' | 'complete') | null;
  primaryChapter?: (number | null) | Chapter;
  managedChapters?: (number | Chapter)[] | null;
  phoneNumber?: string | null;
  ruetDepartment?: string | null;
  graduationYear?: number | null;
  alumniReference?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  employer?: string | null;
  professionalTitle?: string | null;
  communicationPreferences?: {
    allowAnnouncements?: boolean | null;
    allowNewsletters?: boolean | null;
    /**
     * Controls optional reminders only. Required security and transaction messages always send.
     */
    allowSystemEmails?: boolean | null;
  };
  termsAcceptedAt?: string | null;
  privacyAcceptedAt?: string | null;
  deletedAt?: string | null;
  anonymizedReference?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Regional chapter profiles, contacts, administrators, and public visibility.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters".
 */
export interface Chapter {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  chapterStatus: 'active' | 'inactive' | 'planning';
  regionOrState?: string | null;
  summary: string;
  description?: string | null;
  chapterAdmins?: (number | User)[] | null;
  contactEmail?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Optional page-level overrides. Site SEO defaults are used when these are empty.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Draft: still being edited. In review: ready for an administrator. Approved: may be published.
   */
  editorialStatus?: ('draft' | 'inReview' | 'approved') | null;
  /**
   * Internal note for the editor and reviewer. This is never exposed publicly.
   */
  reviewNote?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  owner?: (number | null) | User;
  chapter?: (number | null) | Chapter;
  visibility: 'public' | 'private';
  alt: string;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauthSessions".
 */
export interface OauthSession {
  id: number;
  tokenHash: string;
  user: number | User;
  provider: 'google';
  expiresAt: string;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paymentProofs".
 */
export interface PaymentProof {
  id: number;
  owner: number | User;
  chapter?: (number | null) | Chapter;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  subject: string;
  message: string;
  topic: 'general' | 'membership' | 'chapter' | 'events' | 'website';
  status: 'new' | 'in_review' | 'closed';
  submittedAt: string;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailDeliveries".
 */
export interface EmailDelivery {
  id: number;
  deduplicationKey: string;
  category: 'system' | 'announcement' | 'newsletter';
  required: boolean;
  recipient: string;
  user?: (number | null) | User;
  campaign?: (number | null) | NewsletterCampaign;
  subject: string;
  template: string;
  status: 'queued' | 'processing' | 'sent' | 'failed' | 'suppressed';
  attempts: number;
  queue: 'transactional' | 'reminders' | 'waitlist' | 'newsletters';
  jobId?: string | null;
  provider?: ('capture' | 'resend') | null;
  providerMessageId?: string | null;
  lastAttemptAt?: string | null;
  sentAt?: string | null;
  scheduledFor?: string | null;
  suppressedReason?: string | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletterCampaigns".
 */
export interface NewsletterCampaign {
  id: number;
  title: string;
  subject: string;
  summary?: string | null;
  body: string;
  audience: 'all' | 'members';
  status: 'draft' | 'scheduled' | 'sending' | 'sent' | 'cancelled' | 'failed';
  scheduledAt?: string | null;
  sendStartedAt?: string | null;
  sentAt?: string | null;
  cancelledAt?: string | null;
  createdBy?: (number | null) | User;
  lastActionBy?: (number | null) | User;
  recipientCount: number;
  queuedCount: number;
  suppressedCount: number;
  failedCount: number;
  /**
   * Sanitized campaign dispatch failure summary.
   */
  sendError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Institutional, informational, contact, and legal pages shown on the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroDescription?: string | null;
  summary?: string | null;
  pageType?: ('standard' | 'institutional' | 'legal') | null;
  legalStatus?: ('placeholder' | 'approved') | null;
  lastReviewedAt?: string | null;
  sections?:
    | {
        /**
         * Optional URL-safe anchor used by legal tables of contents.
         */
        anchor?: string | null;
        eyebrow?: string | null;
        title: string;
        body: string;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Optional page-level overrides. Site SEO defaults are used when these are empty.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Draft: still being edited. In review: ready for an administrator. Approved: may be published.
   */
  editorialStatus?: ('draft' | 'inReview' | 'approved') | null;
  /**
   * Internal note for the editor and reviewer. This is never exposed publicly.
   */
  reviewNote?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Articles, resources, and organization news for the learning hub.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt: string;
  body: string;
  /**
   * Preferred rich article body. The plain body remains as a legacy fallback.
   */
  richBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  categories?: (number | Category)[] | null;
  authorName?: string | null;
  readingTimeMinutes?: number | null;
  featured?: boolean | null;
  contentType?: ('article' | 'resource' | 'news') | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Optional page-level overrides. Site SEO defaults are used when these are empty.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Draft: still being edited. In review: ready for an administrator. Approved: may be published.
   */
  editorialStatus?: ('draft' | 'inReview' | 'approved') | null;
  /**
   * Internal note for the editor and reviewer. This is never exposed publicly.
   */
  reviewNote?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Date-windowed public and member notices for the organization or a chapter.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  summary: string;
  details?: string | null;
  chapter?: (number | null) | Chapter;
  audience: 'public' | 'members';
  tone?: ('info' | 'success' | 'alert') | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  activeFrom?: string | null;
  activeTo?: string | null;
  publishedAt?: string | null;
  /**
   * Draft: still being edited. In review: ready for an administrator. Approved: may be published.
   */
  editorialStatus?: ('draft' | 'inReview' | 'approved') | null;
  /**
   * Internal note for the editor and reviewer. This is never exposed publicly.
   */
  reviewNote?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapterRequests".
 */
export interface ChapterRequest {
  id: number;
  requestedName: string;
  requestedRegion?: string | null;
  motivation?: string | null;
  requester: number | User;
  status: 'pending' | 'approved' | 'rejected';
  notes?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  resultingChapter?: (number | null) | Chapter;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membershipPlans".
 */
export interface MembershipPlan {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  publicSummary?: string | null;
  benefits?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  renewalPolicy: string;
  termsSummary: string;
  annualPrice: number;
  currency: string;
  active?: boolean | null;
  renewalReminderEnabled?: boolean | null;
  renewalReminderDaysBefore?: number | null;
  gracePeriodDays?: number | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  user: number | User;
  plan: number | MembershipPlan;
  status:
    | 'pending_payment'
    | 'pending_manual_approval'
    | 'active'
    | 'grace_period'
    | 'expired'
    | 'failed_manual_payment'
    | 'cancelled_by_admin'
    | 'suspended';
  membershipKind: 'join' | 'renewal' | 'reactivation';
  previousMembership?: (number | null) | Membership;
  startedAt?: string | null;
  renewalAt?: string | null;
  expiresAt?: string | null;
  graceEndsAt?: string | null;
  paymentMethod: 'zelle';
  chapterAttribution?: (number | null) | Chapter;
  chapterNameSnapshot?: string | null;
  planTitleSnapshot: string;
  planPriceSnapshot: number;
  currencySnapshot: string;
  billingIntervalSnapshot: string;
  gracePeriodDaysSnapshot: number;
  renewalReminderEnabledSnapshot: boolean;
  renewalReminderDaysBeforeSnapshot: number;
  reactivationEligible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Chapter programs, registration rules, capacity, pricing, and post-event recaps.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  chapter: number | Chapter;
  status: 'draft' | 'published' | 'archived';
  eventMode: 'inPerson' | 'virtual' | 'hybrid';
  startAt: string;
  endAt: string;
  timezone: 'America/New_York' | 'America/Chicago' | 'America/Denver' | 'America/Los_Angeles';
  venue?: string | null;
  virtualLink?: string | null;
  virtualAccessVisibility?: ('public' | 'registered') | null;
  summary: string;
  details?: string | null;
  featuredImage?: (number | null) | Media;
  isPaid?: boolean | null;
  basePrice?: number | null;
  currency?: string | null;
  capacity?: number | null;
  /**
   * Optional. If empty, registration is available as soon as the event is published.
   */
  registrationOpensAt?: string | null;
  /**
   * Optional. If empty, registration closes when the event starts.
   */
  registrationClosesAt?: string | null;
  waitlistEnabled?: boolean | null;
  /**
   * Hours a promoted attendee has to accept an available-seat offer.
   */
  waitlistOfferHours: number;
  maxRegistrationQuantity?: number | null;
  galleryAfterCompletion?: (number | Media)[] | null;
  /**
   * Optional public recap shown after the event ends.
   */
  recapSummary?: string | null;
  publishedAt?: string | null;
  /**
   * Optional page-level overrides. Site SEO defaults are used when these are empty.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Draft: still being edited. In review: ready for an administrator. Approved: may be published.
   */
  editorialStatus?: ('draft' | 'inReview' | 'approved') | null;
  /**
   * Internal note for the editor and reviewer. This is never exposed publicly.
   */
  reviewNote?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  user: number | User;
  quantity: number;
  status: 'pending' | 'confirmed' | 'waitlisted' | 'cancelled';
  order?: (number | null) | Order;
  paymentStatus?: ('pending' | 'paid' | 'failed') | null;
  registrationPriceSnapshot: number;
  unitPriceSnapshot: number;
  currencySnapshot: string;
  eventTitleSnapshot: string;
  eventStartAtSnapshot: string;
  chapterNameSnapshot: string;
  waitlistEntry?: (number | null) | WaitlistEntry;
  discountSnapshot: number;
  waitlistPosition?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  user: number | User;
  orderType: 'membership' | 'event';
  chapterAttribution?: (number | null) | Chapter;
  status: 'pending' | 'paid' | 'failed' | 'cancelled';
  subtotal: number;
  discountTotal?: number | null;
  total: number;
  currency: string;
  paymentMethod: 'zelle';
  membership?: (number | null) | Membership;
  eventRegistration?: (number | null) | EventRegistration;
  promotion?: (number | null) | Promotion;
  promotionCodeSnapshot?: string | null;
  promotionDiscountTypeSnapshot?: ('fixed' | 'percent') | null;
  promotionDiscountValueSnapshot?: number | null;
  chapterNameSnapshot?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  code: string;
  scope: 'membership' | 'event' | 'both';
  discountType: 'fixed' | 'percent';
  discountValue: number;
  startsAt?: string | null;
  endsAt?: string | null;
  usageLimit?: number | null;
  active?: boolean | null;
  memberOnly?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlistEntries".
 */
export interface WaitlistEntry {
  id: number;
  event: number | Event;
  user: number | User;
  quantity: number;
  joinedAt: string;
  status: 'waiting' | 'promoted' | 'accepted' | 'expired';
  promotedAt?: string | null;
  promotionExpiryAt?: string | null;
  acceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  user: number | User;
  order: number | Order;
  paymentSource: 'zelle';
  status: 'pending' | 'approved' | 'failed';
  proofImage?: (number | null) | PaymentProof;
  proofTransactionId?: string | null;
  submittedAt: string;
  amountSnapshot: number;
  currencySnapshot: string;
  orderTypeSnapshot: 'membership' | 'event';
  chapterNameSnapshot?: string | null;
  firstReviewerChapter?: (number | null) | Chapter;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  approvedByRoleSnapshot?: string | null;
  rejectedBy?: (number | null) | User;
  rejectedAt?: string | null;
  rejectedByRoleSnapshot?: string | null;
  rejectionReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs".
 */
export interface AuditLog {
  id: number;
  actor?: (number | null) | User;
  actorRoleSnapshot?: string | null;
  action: string;
  entityType: string;
  entityID: string;
  outcome: 'succeeded' | 'rejected' | 'no_change';
  beforeStatus?: string | null;
  afterStatus?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * National and chapter leadership terms, members, roles, and program recaps.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committeeTerms".
 */
export interface CommitteeTerm {
  id: number;
  committeeType: 'running' | 'advisory';
  chapter?: (number | null) | Chapter;
  title: string;
  summary?: string | null;
  startDate: string;
  endDate: string;
  isCurrent?: boolean | null;
  members?:
    | {
        name: string;
        role: string;
        photo?: (number | null) | Media;
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  eventRecaps?:
    | {
        title: string;
        eventDate?: string | null;
        summary: string;
        photoGallery?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Draft: still being edited. In review: ready for an administrator. Approved: may be published.
   */
  editorialStatus?: ('draft' | 'inReview' | 'approved') | null;
  /**
   * Internal note for the editor and reviewer. This is never exposed publicly.
   */
  reviewNote?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Chronological milestones, supporting media, documents, and external records.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "historyEntries".
 */
export interface HistoryEntry {
  id: number;
  title: string;
  startYear: number;
  endYear?: number | null;
  summary: string;
  body?: string | null;
  sortOrder: number;
  featured?: boolean | null;
  images?: (number | Media)[] | null;
  documents?: (number | Media)[] | null;
  externalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Draft: still being edited. In review: ready for an administrator. Approved: may be published.
   */
  editorialStatus?: ('draft' | 'inReview' | 'approved') | null;
  /**
   * Internal note for the editor and reviewer. This is never exposed publicly.
   */
  reviewNote?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'deliverEmail'
          | 'eventLifecycle'
          | 'membershipLifecycle'
          | 'newsletterLifecycle'
          | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | ('inline' | 'deliverEmail' | 'eventLifecycle' | 'membershipLifecycle' | 'newsletterLifecycle' | 'schedulePublish')
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'oauthSessions';
        value: number | OauthSession;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'paymentProofs';
        value: number | PaymentProof;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'contactSubmissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'emailDeliveries';
        value: number | EmailDelivery;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'chapters';
        value: number | Chapter;
      } | null)
    | ({
        relationTo: 'chapterRequests';
        value: number | ChapterRequest;
      } | null)
    | ({
        relationTo: 'membershipPlans';
        value: number | MembershipPlan;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'eventRegistrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'waitlistEntries';
        value: number | WaitlistEntry;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'auditLogs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'committeeTerms';
        value: number | CommitteeTerm;
      } | null)
    | ({
        relationTo: 'historyEntries';
        value: number | HistoryEntry;
      } | null)
    | ({
        relationTo: 'newsletterCampaigns';
        value: number | NewsletterCampaign;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  accountStatus?: T;
  authMethods?: T;
  googleSubject?: T;
  profileStatus?: T;
  primaryChapter?: T;
  managedChapters?: T;
  phoneNumber?: T;
  ruetDepartment?: T;
  graduationYear?: T;
  alumniReference?: T;
  city?: T;
  state?: T;
  country?: T;
  employer?: T;
  professionalTitle?: T;
  communicationPreferences?:
    | T
    | {
        allowAnnouncements?: T;
        allowNewsletters?: T;
        allowSystemEmails?: T;
      };
  termsAcceptedAt?: T;
  privacyAcceptedAt?: T;
  deletedAt?: T;
  anonymizedReference?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauthSessions_select".
 */
export interface OauthSessionsSelect<T extends boolean = true> {
  tokenHash?: T;
  user?: T;
  provider?: T;
  expiresAt?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  owner?: T;
  chapter?: T;
  visibility?: T;
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paymentProofs_select".
 */
export interface PaymentProofsSelect<T extends boolean = true> {
  owner?: T;
  chapter?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  topic?: T;
  status?: T;
  submittedAt?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailDeliveries_select".
 */
export interface EmailDeliveriesSelect<T extends boolean = true> {
  deduplicationKey?: T;
  category?: T;
  required?: T;
  recipient?: T;
  user?: T;
  campaign?: T;
  subject?: T;
  template?: T;
  status?: T;
  attempts?: T;
  queue?: T;
  jobId?: T;
  provider?: T;
  providerMessageId?: T;
  lastAttemptAt?: T;
  sentAt?: T;
  scheduledFor?: T;
  suppressedReason?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  heroEyebrow?: T;
  heroTitle?: T;
  heroDescription?: T;
  summary?: T;
  pageType?: T;
  legalStatus?: T;
  lastReviewedAt?: T;
  sections?:
    | T
    | {
        anchor?: T;
        eyebrow?: T;
        title?: T;
        body?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  editorialStatus?: T;
  reviewNote?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  body?: T;
  richBody?: T;
  featuredImage?: T;
  categories?: T;
  authorName?: T;
  readingTimeMinutes?: T;
  featured?: T;
  contentType?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  editorialStatus?: T;
  reviewNote?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  details?: T;
  chapter?: T;
  audience?: T;
  tone?: T;
  ctaLabel?: T;
  ctaHref?: T;
  activeFrom?: T;
  activeTo?: T;
  publishedAt?: T;
  editorialStatus?: T;
  reviewNote?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters_select".
 */
export interface ChaptersSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  chapterStatus?: T;
  regionOrState?: T;
  summary?: T;
  description?: T;
  chapterAdmins?: T;
  contactEmail?: T;
  heroImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  editorialStatus?: T;
  reviewNote?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapterRequests_select".
 */
export interface ChapterRequestsSelect<T extends boolean = true> {
  requestedName?: T;
  requestedRegion?: T;
  motivation?: T;
  requester?: T;
  status?: T;
  notes?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  resultingChapter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membershipPlans_select".
 */
export interface MembershipPlansSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  publicSummary?: T;
  benefits?:
    | T
    | {
        label?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  renewalPolicy?: T;
  termsSummary?: T;
  annualPrice?: T;
  currency?: T;
  active?: T;
  renewalReminderEnabled?: T;
  renewalReminderDaysBefore?: T;
  gracePeriodDays?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  user?: T;
  plan?: T;
  status?: T;
  membershipKind?: T;
  previousMembership?: T;
  startedAt?: T;
  renewalAt?: T;
  expiresAt?: T;
  graceEndsAt?: T;
  paymentMethod?: T;
  chapterAttribution?: T;
  chapterNameSnapshot?: T;
  planTitleSnapshot?: T;
  planPriceSnapshot?: T;
  currencySnapshot?: T;
  billingIntervalSnapshot?: T;
  gracePeriodDaysSnapshot?: T;
  renewalReminderEnabledSnapshot?: T;
  renewalReminderDaysBeforeSnapshot?: T;
  reactivationEligible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  chapter?: T;
  status?: T;
  eventMode?: T;
  startAt?: T;
  endAt?: T;
  timezone?: T;
  venue?: T;
  virtualLink?: T;
  virtualAccessVisibility?: T;
  summary?: T;
  details?: T;
  featuredImage?: T;
  isPaid?: T;
  basePrice?: T;
  currency?: T;
  capacity?: T;
  registrationOpensAt?: T;
  registrationClosesAt?: T;
  waitlistEnabled?: T;
  waitlistOfferHours?: T;
  maxRegistrationQuantity?: T;
  galleryAfterCompletion?: T;
  recapSummary?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  editorialStatus?: T;
  reviewNote?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  quantity?: T;
  status?: T;
  order?: T;
  paymentStatus?: T;
  registrationPriceSnapshot?: T;
  unitPriceSnapshot?: T;
  currencySnapshot?: T;
  eventTitleSnapshot?: T;
  eventStartAtSnapshot?: T;
  chapterNameSnapshot?: T;
  waitlistEntry?: T;
  discountSnapshot?: T;
  waitlistPosition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlistEntries_select".
 */
export interface WaitlistEntriesSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  quantity?: T;
  joinedAt?: T;
  status?: T;
  promotedAt?: T;
  promotionExpiryAt?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  user?: T;
  orderType?: T;
  chapterAttribution?: T;
  status?: T;
  subtotal?: T;
  discountTotal?: T;
  total?: T;
  currency?: T;
  paymentMethod?: T;
  membership?: T;
  eventRegistration?: T;
  promotion?: T;
  promotionCodeSnapshot?: T;
  promotionDiscountTypeSnapshot?: T;
  promotionDiscountValueSnapshot?: T;
  chapterNameSnapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  user?: T;
  order?: T;
  paymentSource?: T;
  status?: T;
  proofImage?: T;
  proofTransactionId?: T;
  submittedAt?: T;
  amountSnapshot?: T;
  currencySnapshot?: T;
  orderTypeSnapshot?: T;
  chapterNameSnapshot?: T;
  firstReviewerChapter?: T;
  approvedBy?: T;
  approvedAt?: T;
  approvedByRoleSnapshot?: T;
  rejectedBy?: T;
  rejectedAt?: T;
  rejectedByRoleSnapshot?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actor?: T;
  actorRoleSnapshot?: T;
  action?: T;
  entityType?: T;
  entityID?: T;
  outcome?: T;
  beforeStatus?: T;
  afterStatus?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  code?: T;
  scope?: T;
  discountType?: T;
  discountValue?: T;
  startsAt?: T;
  endsAt?: T;
  usageLimit?: T;
  active?: T;
  memberOnly?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committeeTerms_select".
 */
export interface CommitteeTermsSelect<T extends boolean = true> {
  committeeType?: T;
  chapter?: T;
  title?: T;
  summary?: T;
  startDate?: T;
  endDate?: T;
  isCurrent?: T;
  members?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        bio?: T;
        id?: T;
      };
  eventRecaps?:
    | T
    | {
        title?: T;
        eventDate?: T;
        summary?: T;
        photoGallery?: T;
        id?: T;
      };
  editorialStatus?: T;
  reviewNote?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "historyEntries_select".
 */
export interface HistoryEntriesSelect<T extends boolean = true> {
  title?: T;
  startYear?: T;
  endYear?: T;
  summary?: T;
  body?: T;
  sortOrder?: T;
  featured?: T;
  images?: T;
  documents?: T;
  externalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  editorialStatus?: T;
  reviewNote?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletterCampaigns_select".
 */
export interface NewsletterCampaignsSelect<T extends boolean = true> {
  title?: T;
  subject?: T;
  summary?: T;
  body?: T;
  audience?: T;
  status?: T;
  scheduledAt?: T;
  sendStartedAt?: T;
  sentAt?: T;
  cancelledAt?: T;
  createdBy?: T;
  lastActionBy?: T;
  recipientCount?: T;
  queuedCount?: T;
  suppressedCount?: T;
  failedCount?: T;
  sendError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Organization identity, contact details, and public Zelle payment instructions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  organizationName: string;
  tagline?: string | null;
  primaryEmail?: string | null;
  chapterSupportEmail?: string | null;
  primaryPhone?: string | null;
  mailingAddress?: string | null;
  contactResponseNote?: string | null;
  utilityMessage?: string | null;
  footerNote?: string | null;
  zelleRecipientName?: string | null;
  /**
   * The approved Zelle email address or US phone number.
   */
  zelleRecipient?: string | null;
  zelleInstructions: string;
  manualPaymentReviewNote: string;
  noRefundNotice: string;
  eventPaymentTerms: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Utility links, primary navigation, menus, and the header action.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  utilityLinks?:
    | {
        link: {
          label: string;
          /**
           * Use an internal path or an HTTP(S), email, or phone destination.
           */
          href: string;
          description?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  mainLinks?:
    | {
        link: {
          label: string;
          /**
           * Use an internal path or an HTTP(S), email, or phone destination.
           */
          href: string;
          description?: string | null;
        };
        /**
         * Optional child destinations displayed in desktop and mobile menus.
         */
        children?:
          | {
              link: {
                label: string;
                /**
                 * Use an internal path or an HTTP(S), email, or phone destination.
                 */
                href: string;
                description?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        featured?: {
          eyebrow?: string | null;
          title?: string | null;
          description?: string | null;
          label?: string | null;
          href?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  primaryCtaLabel: string;
  primaryCtaHref: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer link groups, legal destinations, newsletter action, and social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  groups?:
    | {
        title: string;
        links?:
          | {
              link: {
                label: string;
                /**
                 * Use an internal path or an HTTP(S), email, or phone destination.
                 */
                href: string;
                description?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletterTitle?: string | null;
  newsletterSummary?: string | null;
  newsletterCtaLabel: string;
  newsletterCtaHref: string;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  legalNotice?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage copy and section labels. Published records populate each content module.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroDescription: string;
  primaryCtaLabel: string;
  primaryCtaHref: string;
  secondaryCtaLabel: string;
  secondaryCtaHref: string;
  networkPanelEyebrow: string;
  networkPanelTitle: string;
  networkPanelDescription: string;
  statsSectionEyebrow?: string | null;
  statsSectionTitle?: string | null;
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  announcementSectionTitle?: string | null;
  announcementSectionDescription?: string | null;
  membershipSectionTitle?: string | null;
  membershipSectionDescription?: string | null;
  chaptersSectionTitle?: string | null;
  chaptersSectionDescription?: string | null;
  eventsSectionTitle?: string | null;
  eventsSectionDescription?: string | null;
  historySectionTitle?: string | null;
  historySectionDescription?: string | null;
  committeesSectionTitle?: string | null;
  committeesSectionDescription?: string | null;
  learningSectionTitle?: string | null;
  learningSectionDescription?: string | null;
  /**
   * Optional page-level overrides. Site SEO defaults are used when these are empty.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Default search and social metadata used when a page has no override.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoDefaults".
 */
export interface SeoDefault {
  id: number;
  siteName?: string | null;
  titleSuffix?: string | null;
  defaultDescription?: string | null;
  defaultImage?: (number | null) | Media;
  /**
   * Optional social handle, including the leading @.
   */
  socialHandle?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  organizationName?: T;
  tagline?: T;
  primaryEmail?: T;
  chapterSupportEmail?: T;
  primaryPhone?: T;
  mailingAddress?: T;
  contactResponseNote?: T;
  utilityMessage?: T;
  footerNote?: T;
  zelleRecipientName?: T;
  zelleRecipient?: T;
  zelleInstructions?: T;
  manualPaymentReviewNote?: T;
  noRefundNotice?: T;
  eventPaymentTerms?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  utilityLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
        id?: T;
      };
  mainLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                  };
              id?: T;
            };
        featured?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              label?: T;
              href?: T;
            };
        id?: T;
      };
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  groups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  newsletterTitle?: T;
  newsletterSummary?: T;
  newsletterCtaLabel?: T;
  newsletterCtaHref?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legalNotice?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroDescription?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  networkPanelEyebrow?: T;
  networkPanelTitle?: T;
  networkPanelDescription?: T;
  statsSectionEyebrow?: T;
  statsSectionTitle?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  announcementSectionTitle?: T;
  announcementSectionDescription?: T;
  membershipSectionTitle?: T;
  membershipSectionDescription?: T;
  chaptersSectionTitle?: T;
  chaptersSectionDescription?: T;
  eventsSectionTitle?: T;
  eventsSectionDescription?: T;
  historySectionTitle?: T;
  historySectionDescription?: T;
  committeesSectionTitle?: T;
  committeesSectionDescription?: T;
  learningSectionTitle?: T;
  learningSectionDescription?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoDefaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  siteName?: T;
  titleSuffix?: T;
  defaultDescription?: T;
  defaultImage?: T;
  socialHandle?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DeliverEmailJobInput".
 */
export interface DeliverEmailJobInput {
  input: {
    deliveryID: number;
    html: string;
    text: string;
  };
  output: {
    deliveryID: number;
    status: 'sent' | 'deduplicated' | 'suppressed';
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventLifecycleJobInput".
 */
export interface EventLifecycleJobInput {
  input?: unknown;
  output: {
    expiredOffers: number;
    promotedOffers: number;
    processedEvents: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MembershipLifecycleJobInput".
 */
export interface MembershipLifecycleJobInput {
  input?: unknown;
  output: {
    expired: number;
    graceStarted: number;
    remindersQueued: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterLifecycleJobInput".
 */
export interface NewsletterLifecycleJobInput {
  input?: unknown;
  output: {
    failedCampaigns: number;
    processedCampaigns: number;
    sentCampaigns: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'announcements';
          value: number | Announcement;
        } | null)
      | ({
          relationTo: 'chapters';
          value: number | Chapter;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null)
      | ({
          relationTo: 'committeeTerms';
          value: number | CommitteeTerm;
        } | null)
      | ({
          relationTo: 'historyEntries';
          value: number | HistoryEntry;
        } | null);
    global?: ('siteSettings' | 'header' | 'footer' | 'home' | 'seoDefaults') | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}